language: ruby
rvm:
  - 3.0.0
install:
  - bundle install --jobs 3 --retry 3
  - RAILS_ENV=test bin/rails db:create
  - RAILS_ENV=test bin/rails db:migrate
script:
  - bin/rails app:ci
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
branches:
  only:
    - main
    - develop
    - /^feature\/.+$/
